import { ConfigPlugin, withDangerousMod } from '@expo/config-plugins';
import * as fs from 'fs';
import * as path from 'path';
import { AutofillPluginOptions } from '../index';

const FLAGS_MODULE = '@tetherto/pearpass-lib-constants/src/constants/flags.js';
const DEFAULT_DESIGN_VERSION = 1;

// Reads DESIGN_VERSION from the shared flags module so the autofill extension
// can read it at runtime via getResources().getInteger(R.integer.design_version).
function readDesignVersion(projectRoot: string): number {
  const flagsPath = path.join(projectRoot, 'node_modules', FLAGS_MODULE);
  if (!fs.existsSync(flagsPath)) {
    console.warn(`[withAndroidDesignVersion] flags.js not found, using ${DEFAULT_DESIGN_VERSION}`);
    return DEFAULT_DESIGN_VERSION;
  }

  const match = fs.readFileSync(flagsPath, 'utf-8').match(/export\s+const\s+DESIGN_VERSION\s*=\s*(\d+)/);
  if (!match) {
    console.warn(`[withAndroidDesignVersion] DESIGN_VERSION not found, using ${DEFAULT_DESIGN_VERSION}`);
    return DEFAULT_DESIGN_VERSION;
  }

  const parsed = parseInt(match[1], 10);
  if (Number.isNaN(parsed)) {
    console.warn(`[withAndroidDesignVersion] DESIGN_VERSION="${match[1]}" not an integer, using ${DEFAULT_DESIGN_VERSION}`);
    return DEFAULT_DESIGN_VERSION;
  }

  console.log(`[withAndroidDesignVersion] Resolved DESIGN_VERSION=${parsed}`);
  return parsed;
}

export const withAndroidDesignVersion: ConfigPlugin<AutofillPluginOptions> = (config) => {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const version = readDesignVersion(cfg.modRequest.projectRoot);

      const valuesDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app/src/main/res/values'
      );
      await fs.promises.mkdir(valuesDir, { recursive: true });

      const xml =
        `<?xml version="1.0" encoding="utf-8"?>\n` +
        `<!-- Generated by withAndroidDesignVersion. Do not edit by hand.\n` +
        `     Source: ${FLAGS_MODULE} -> DESIGN_VERSION -->\n` +
        `<resources>\n` +
        `    <integer name="design_version">${version}</integer>\n` +
        `</resources>\n`;

      const target = path.join(valuesDir, 'design_version.xml');
      await fs.promises.writeFile(target, xml, 'utf-8');

      return cfg;
    },
  ]);
};
